# Generated by Django 4.0.6 on 2022-07-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_l_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='l_winner',
        ),
    ]
