# Generated by Django 4.0.6 on 2022-07-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionlisting_l_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
