# Generated by Django 4.0.6 on 2022-07-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='l_category',
            field=models.CharField(default='Other', max_length=32),
        ),
    ]
