# Generated by Django 4.1 on 2022-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_strategycall_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategycall",
            name="trade_status",
            field=models.CharField(default="closed", max_length=8),
        ),
    ]
