# Generated by Django 4.1 on 2022-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_strategyparam_calls_denomination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategyparam",
            name="calls_denomination",
        ),
        migrations.AddField(
            model_name="symbol",
            name="calls_denomination",
            field=models.CharField(default="pontos", max_length=16),
        ),
    ]
